### PR TITLE
Resolve some bugs

### PR DESCRIPTION
**Pull request by SimonLab**
typo loaion [issue20](https://github.com/akitten/linkedin-public-profile-parser/issues/20)
don't save profile files [issue27](https://github.com/akitten/linkedin-public-profile-parser/issues/27)
links badge to akitten instead of nelsonic
get the correct current position [issue26](https://github.com/akitten/linkedin-public-profile-parser/issues/26)
fixes DOM fail (latest profile page version!): https://github.com/akitten/linkedin-public-profile-parser/issues/30

### CODE REVIEW

**Comment by nelsonic** [comment]
@SimonLab the changes you have made to the code seem good.
Do you have an idea why the Travis build is failing: https://travis-ci.org/akitten/linkedin-public-profile-parser/builds/87349434#L214-L234 ?

its worth `console.log`ing the statusCode for the response https://github.com/akitten/linkedin-public-profile-parser/blob/dfd95168785fa6cb2985322da7dd4d4ca00c3b0c/lib/fetcher.js#L24 so you know what they are saying. I suspect they are sending a `999` code or similar with zero content because they don't let us send direct requests from Travis...

**Comment by SimonLab** [comment]
I did a console.log in the test who was failing (elon profile), I can't find it anymore I might have delete it. I remember that the status code was 404. Is it right to think that Travis is using Amazon and that's why linkedIn is blocking the request? Should we use [codeship](https://codeship.com/) instead of Travis?

**Comment by nelsonic** [comment]
Codeship will also be blocked by LinkedIn because they run on AWS.
The `response.statusCode` will not be 404.
The error code is being _manually_ set on line 19 when the request fails ... see: https://github.com/akitten/linkedin-public-profile-parser/blob/dfd95168785fa6cb2985322da7dd4d4ca00c3b0c/lib/fetcher.js#L19

**Comment by SimonLab** [comment]
LinkedIn change some classes of the DOM profiles page, so that may be why the tests fail. I'm looking exactly what are the changes on the DOM. The names of the DOM element of a profile is also different if you are connected to LinkedIn or not

**Comment by nelsonic** [comment]
The UI (DOM Classes/Structure) will change over time. that's why we have tests.
Let me know if you want to pair on updating the `lib/profile.js` script to reflect the new DOM...

**Comment by SimonLab** [comment]
Most of the tests was working again this morning. After more investigation I think that LinkedIn is serving (randomly?) a different DOM. It also looks like for now that it exists only 2 DOM version of a profile!

**Comment by nelsonic** [comment]
@SimonLab I've updated the parser for the latest DOM on profile pages. :white_check_mark: 
_Confirm_ by pull on this branch and run `npm run full` :wink: 
@iteles please review and merge. thanks. :rocket:

**Comment by iteles** [comment]
You've been busy! 👌🏻

**Pull request merged**
