### PR TITLE
return different type of errors

### PR DESCRIPTION
**Pull request by SimonLab**
see #34 

return 3 different kind of errors: 'url undefined', '404' and 'error fetcher'

@nelsonic what do you think about this PR?

### CODE REVIEW

**Comment by nelsonic** [comment]
@SimonLab only one test is failing: https://travis-ci.org/akitten/linkedin-public-profile-parser/builds/108514398#L207 please ping me when it passes. :+1:

**Comment by SimonLab** [comment]
LinkedIn is not a big fan of Travis so when we try to get some error status it can return a 999 status code instead of a normal 404
see http://stackoverflow.com/questions/27231113/999-error-code-on-head-request-to-linkedin

**Comment by nelsonic** [comment]
@SimonLab looks good. please update the version in `package.json` so we can `npm publish` thanks.

**Comment by SimonLab** [comment]
:+1:

**Comment by nelsonic** [comment]
merging.

**Comment by nelsonic** [comment]
@SimonLab new version on NPM: `3.0.2` :+1:

**Pull request merged**
